### ISSUE TITLE
Support for FusionAuth

### ISSUE THREAD

**Issue by ethantmcgee** [m-barthelemy/vpn-webauth#17]
FusionAuth is a self-hostable OAuth2 Provider (https://fusionauth.io/).  It is used by several companies in the area where I live, and we decided that we wanted to use this project authenticating against that backend to give us more control over the auth process. 

We managed to get the process mostly working, and in the spirit of open source, would like to contribute our changes back.  However, I don't see a contribution procedure for this repository.

1) Are you open to accepting changes from others?
2) How would you like us to go about submitting the changes for review?

**Comment by m-barthelemy** [comment]
Hey, if you want to add another authentication provider to this project, you are of course free to do so. 
Any contribution will always be welcome.
You can submit PRs - if this workflow is not suitable for you let me know.
Note that it may take me a little while to review/reply, but I'll be happy to do so.

**Comment by ethantmcgee** [comment]
@m-barthelemy I have opened a pull request for you (https://github.com/m-barthelemy/vpn-webauth/pull/18)

Thank you for agreeing to accept the contribution.
